### ISSUE TITLE
Pydantic throws an error when import types

### ISSUE THREAD

**Issue by eavanvalkenburg** [google/generative-ai-python#102]
### Description of the bug:

When using classes from types in other classes which use pydantic, pydantic throws this error:
`pydantic.errors.PydanticUserError: Please use `typing_extensions.TypedDict` instead of `typing.TypedDict` on Python < 3.12.` 

### Actual vs expected behavior:

No error

### Any other information you'd like to share?

Should be an easy fix to add:
```python
import sys
if sys.version_info >= (3, 12):
    from typing import TypedDict
else:
    from typing_extensions import TypedDict
```

**Comment by keertk** [comment]
Hi @eavanvalkenburg thanks for the report. Would you be willing to submit a PR with the fix?

**Comment by eavanvalkenburg** [comment]
I created a PR for this one.
