### ISSUE TITLE
Responses without candidates throwing IndexError

### ISSUE THREAD

**Issue by markmcd** [google/generative-ai-python#113]
### Description of the bug:

e.g.
![image](https://github.com/google/generative-ai-python/assets/109308/6bcd6ed3-aaa3-4696-a492-1a2b871b798a)

I think ideally this would error with a relevant error message.

**Comment by persianopencart** [comment]
@markmcd 
Hi, is there any update for this issue?

**Comment by MarkDaoust** [comment]
I think this is fixed by https://github.com/google/generative-ai-python/pull/138.

I don't see another way this code can throw an index error. 


https://github.com/google/generative-ai-python/blob/main/google/generativeai/types/generation_types.py#L286-L335

**Comment by MarkDaoust** [comment]
But LMK if I'm wrong, please send code to reproduce.
