### ISSUE TITLE
“1‘ is blocked by safety reason? seriously

### ISSUE THREAD

**Issue by Andy963** [google/generative-ai-python#126]
### Description of the bug:

when i send 1 to the gemini pro, it raise a exception :
ValueError: The `response.parts` quick accessor only works for a single candidate, but none were returned. Check the `response.prompt_feedback` to see if the prompt was blocked.

then i print the response.prommpt_feedback, i got this:

block_reason: SAFETY
safety_ratings {
  category: HARM_CATEGORY_SEXUALLY_EXPLICIT
  probability: NEGLIGIBLE
}
safety_ratings {
  category: HARM_CATEGORY_HATE_SPEECH
  probability: LOW
}
safety_ratings {
  category: HARM_CATEGORY_HARASSMENT
  probability: MEDIUM
}
safety_ratings {
  category: HARM_CATEGORY_DANGEROUS_CONTENT
  probability: NEGLIGIBLE
}
them i go to studio ：

![image](https://github.com/google/generative-ai-python/assets/16980400/9081f628-12c8-4828-9f5c-00673b1f84d8)

### Actual vs expected behavior:

so anybody tell what happend?
_No response_

**Comment by DiamondGo** [comment]
The same here. lmfao.

API level censorship is stupid.

**Comment by alexmavr** [comment]
same here, I'm running the API over an eval dataset and it won't finish the full dataset run. If this is rate limiting then at least clearly say so

**Comment by LaMerdaSeca** [comment]
I have the same error in Java: The response is blocked due to safety reason
even in my settings I have: 
```
setSafetySettings(Collections.singletonList(
                    SafetySetting.newBuilder()
                            .setThreshold(SafetySetting
                                    .HarmBlockThreshold.BLOCK_NONE).build()));
```

**Comment by elavalasrinivasreddy** [comment]
Same here. I got a response for below numbers, for remaining numbers same error.
0 : Got the defination of Zero
6 : Got the explanation of Hexagone
10 :  Got these subpoints 
> 1. Computer Programming
> 2. Machine Learning
> 3. Data Analysis
> 4. Web Development
> 5. Digital Marketing
> 6. Graphic Design
> 7. Video Editing
> 8. 3D Modeling and Animation
> 9. Photography
> 10. Music Production

**Comment by Roviky** [comment]
I meet this problem too.How can i run it again?

**Comment by HienBM** [comment]
Try setting the probability with ‘BLOCK_NONE’. I ran it successfully with that.

block_reason: SAFETY
safety_ratings {
category: HARM_CATEGORY_SEXUALLY_EXPLICIT
probability: BLOCK_NONE
}
safety_ratings {
category: HARM_CATEGORY_HATE_SPEECH
probability: BLOCK_NONE
}
safety_ratings {
category: HARM_CATEGORY_HARASSMENT
probability: BLOCK_NONE
}
safety_ratings {
category: HARM_CATEGORY_DANGEROUS_CONTENT
probability: BLOCK_NONE
}

**Comment by jacklanda** [comment]
> Try setting the probability with ‘BLOCK_NONE’. I ran it successfully with that.
> 
> block_reason: SAFETY safety_ratings { category: HARM_CATEGORY_SEXUALLY_EXPLICIT probability: BLOCK_NONE } safety_ratings { category: HARM_CATEGORY_HATE_SPEECH probability: BLOCK_NONE } safety_ratings { category: HARM_CATEGORY_HARASSMENT probability: BLOCK_NONE } safety_ratings { category: HARM_CATEGORY_DANGEROUS_CONTENT probability: BLOCK_NONE }

Where should I set up this argument?

**Comment by HienBM** [comment]
> > Try setting the probability with ‘BLOCK_NONE’. I ran it successfully with that.
> > block_reason: SAFETY safety_ratings { category: HARM_CATEGORY_SEXUALLY_EXPLICIT probability: BLOCK_NONE } safety_ratings { category: HARM_CATEGORY_HATE_SPEECH probability: BLOCK_NONE } safety_ratings { category: HARM_CATEGORY_HARASSMENT probability: BLOCK_NONE } safety_ratings { category: HARM_CATEGORY_DANGEROUS_CONTENT probability: BLOCK_NONE }
> 
> Where should I set up this argument?

This is my set up

![Screenshot 2024-01-14 075915](https://github.com/google/generative-ai-python/assets/68155289/fbbcef41-f931-4039-9bed-9220234740da)

**Comment by jacklanda** [comment]
> > > Try setting the probability with ‘BLOCK_NONE’. I ran it successfully with that.
> > > block_reason: SAFETY safety_ratings { category: HARM_CATEGORY_SEXUALLY_EXPLICIT probability: BLOCK_NONE } safety_ratings { category: HARM_CATEGORY_HATE_SPEECH probability: BLOCK_NONE } safety_ratings { category: HARM_CATEGORY_HARASSMENT probability: BLOCK_NONE } safety_ratings { category: HARM_CATEGORY_DANGEROUS_CONTENT probability: BLOCK_NONE }
> > 
> > 
> > Where should I set up this argument?
> 
> This is my set up
> 
> ![Screenshot 2024-01-14 075915](https://private-user-images.githubusercontent.com/68155289/296523860-fbbcef41-f931-4039-9bed-9220234740da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMDMxMjUsIm5iZiI6MTcwNTIwMjgyNSwicGF0aCI6Ii82ODE1NTI4OS8yOTY1MjM4NjAtZmJiY2VmNDEtZjkzMS00MDM5LTliZWQtOTIyMDIzNDc0MGRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDAzMjcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhMDVjMWE2ZWMwOWY3NDIwNTBmNmQ1ZDdhNDY0NWE5MmU3OWY4ODljYTNkMDBhMjEyNzI1YTMzOTI5OTIwODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VvyAd94snSgVryu5ceU6ZLlvV_tgUAL0sFtx0xQMBrI)

It does work. A simple but effective solution to it. Thank you so much!

**Comment by teddythinh** [comment]
I'm getting this error while using a for loop to feed the model questions and response answers.

Here is how I configure the model:

```python
generation_config = {
  "candidate_count": 1,
  "max_output_tokens": 256,
  "temperature": 1.0,
  "top_p": 0.7,
}

safety_settings=[
  {
    "category": "HARM_CATEGORY_DANGEROUS",
    "threshold": "BLOCK_NONE",
  },
  {
    "category": "HARM_CATEGORY_HARASSMENT",
    "threshold": "BLOCK_NONE",
  },
  {
    "category": "HARM_CATEGORY_HATE_SPEECH",
    "threshold": "BLOCK_NONE",
  },
  {
    "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
    "threshold": "BLOCK_NONE",
  },
  {
    "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
    "threshold": "BLOCK_NONE",
  },
]

model = genai.GenerativeModel(
    model_name="gemini-pro",
    generation_config=generation_config,
    safety_settings=safety_settings
)
```

And here is how I run it:

```python
response=None
timeout_counter=0
    while response is None and timeout_counter<=30:
        try:
            response = model.generate_content(messages)
        except Exception as msg:
            pprint(msg)
            print('sleeping because of exception ...')
            time.sleep(30)
            continue

    if response==None:
        response_str=""
    else:
        response_str = response.text # <- This line gets error
```

**Comment by Marwa-Essam81** [comment]
I am also getting block_reason: OTHER even through I have set all safety settings to BLOCK_NONE

**Comment by Yinhance** [comment]
> I am also getting block_reason: OTHER even through I have set all safety settings to BLOCK_NONE

Have u solved this promble?

**Comment by deepak032002** [comment]
Try this it works for me - 

import {
  GoogleGenerativeAI,
  HarmCategory,
  HarmBlockThreshold,
} from '@google/generative-ai';
import { ConfigService } from '@nestjs/config';

const config = new ConfigService();

export async function generateText(data: string, type: 'title' | 'content') {

  const genAI = new GoogleGenerativeAI(config.get('GOOGLE_GEMINI_API_KEY'));
  const model = genAI.getGenerativeModel({ model: 'gemini-pro' });

  const generationConfig = {
    temperature: 0.9,
    topK: 1,
    topP: 1,
    maxOutputTokens: 2048,
  };

  const safetySettings = [
    {
      category: HarmCategory.HARM_CATEGORY_HARASSMENT,
      threshold: HarmBlockThreshold.BLOCK_NONE,
    },
    {
      category: HarmCategory.HARM_CATEGORY_HATE_SPEECH,
      threshold: HarmBlockThreshold.BLOCK_NONE,
    },
    {
      category: HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT,
      threshold: HarmBlockThreshold.BLOCK_NONE,
    },
    {
      category: HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
      threshold: HarmBlockThreshold.BLOCK_NONE,
    },
  ];

  const history = [];

  const chat = model.startChat({
    generationConfig,
    safetySettings,
    history,
  });

  let msg: string = "YOUR_MESSAGE";

  const result = await chat.sendMessage(msg);
  const response = result.response;
  const text = response.text();
  return text.replaceAll('\n', '<br/>');
}

**Comment by gunsterpsp** [comment]
GoogleGenerativeAIResponseError: [GoogleGenerativeAI Error]: Candidate was blocked due to RECITATION
    at response.text (file:///F:/oliverbackup/flutter_app/backend/node_modules/@google/generative-ai/dist/index.mjs:265:23)
    at getAIResponse (file:///F:/oliverbackup/flutter_app/backend/controllers/MessagesController.js:148:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  response: {
    candidates: [ [Object] ],
    promptFeedback: { safetyRatings: [Array] },
    text: [Function (anonymous)]
  }
}

how about this one?

**Comment by jacklanda** [comment]
Please consider reopening this closed issue or filing another one for further discussion.

**Comment by miRx923** [comment]
I'm here to tell you how I find out to avoid the "block_reason: OTHER" error.

I have no clue why the error occurs and what does it mean, but if you're fine with just skipping the prompt that causes the error, there is a fix for it. I'm analysing sentiment of the rewievs in a .csv file and if the "block_reason: OTHER" occurs I just return "incorrect" instead of "positive" or "negative". If this method doesn't fit in your use case, you try to adjust it.

#### Python code:
```
    safety_settings=[
    {
        "category": "HARM_CATEGORY_HARASSMENT",
        "threshold": "BLOCK_NONE",
    },
    {
        "category": "HARM_CATEGORY_HATE_SPEECH",
        "threshold": "BLOCK_NONE",
    },
    {
        "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
        "threshold": "BLOCK_NONE",
    },
    {
        "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
        "threshold": "BLOCK_NONE",
    },
    ]

    model = genai.GenerativeModel("gemini-pro", generation_config=generation_config, safety_settings=safety_settings)
    chat = model.start_chat(history=[])

      try:
          response = chat.send_message(prompt)
          
          if response:
              output = response.text
              sentiment = output.strip()
              
      
      # Handle the blocked prompt exception
      except genai.types.generation_types.BlockedPromptException as e:
          print(f"Prompt blocked due to: {e}")

          return "incorrect"

      time.sleep(0.25) # you can skip this line

      return sentiment
```      

This way, when I encounter the error it just returns "incorrect" and continues with the next prompt. Hope I helped. ❤️

**Comment by pranavkshirsagar1924** [comment]
well In my case the problem was due to explicit prompt

**Comment by neil564** [comment]
easy solution just use open ai instead of gemini lol
