### ISSUE TITLE
Does generative language api support something to set location?

### ISSUE THREAD

**Issue by Junjie-Chu** [google/generative-ai-python#135]
I find that there is a way to set the location in vertex ai:
```
from google.cloud import aiplatform
import vertexai
from vertexai.language_models import TextGenerationModel

project_id = "test"
location = "us-central1"

vertexai.init(project=project_id, location=location)
```

Is there any method to do the same thing in generative language api (this repository)?

**Comment by rabilrbl** [comment]
@Junjie-Chu 
As of my knowledge you can't. It is only possible for Google cloud VertexAI users.
See the migration guide to know the difference with Google AI Studio and Vertex AI
https://cloud.google.com/vertex-ai/docs/generative-ai/migrate/migrate-google-ai#google-ai

**Comment by ishaangandhi** [comment]
How do you see what region you're using?

**Comment by MarkDaoust** [comment]
@ishaangandhi I think the API just does some GeoIP-lookup on the request.
