### ISSUE TITLE
JSON Mode

### ISSUE THREAD

**Issue by Lord-Haji** [google/generative-ai-python#137]
### Description of the feature request:

Didn't the announcement video specifically mention about json mode? I'm unable to find a flag for it in the API. and asking to `gemini-pro` to send a JSON output returns invalid json data

### What problem are you trying to solve with this feature?

JSON parsable output for building apps

**Comment by MarkDaoust** [comment]
Can you give me a reference? I can't find any mention of this.

Maybe you're referring to function calling? We're working on better documentation  and support, but it does allow you to define a function and the input schema, and if it returns a FunctionCall instead of a test response, the FunctionCall uses the described schema.

Example [WIP]: https://github.com/MarkDaoust/generative-ai-docs/blob/function-docs/site/en/tutorials/function_calling_python_quickstart.ipynb

**Comment by Lord-Haji** [comment]
I am probably mistaken then. The feature I was talking about is Gemini returning parsable JSON Strings for normal questions too. Makes it follow a pattern for production apps using Gemini This is something which OpenAI brought to their Client in November. Although Gemini does send Valid JSONS from my tests up until now if asked in the prompt but the Formatting of the completion is messed up. 
Sometimes it adds a

- Here is the JSON you requested for
- "```JSON ... ```"
- And sometimes it doesn't do any of it
- 
Which can honestly be fixed with a Regex
It would be great if there was a first party JSON mode implementation abstracting that from the developers

> Can you give me a reference? I can't find any mention of this.
> 
> Maybe you're referring to function calling? We're working on better documentation and support, but it does allow you to define a function and the input schema, and if it returns a FunctionCall instead of a test response, the FunctionCall uses the described schema.
> 
> Example [WIP]: https://github.com/MarkDaoust/generative-ai-docs/blob/function-docs/site/en/tutorials/function_calling_python_quickstart.ipynb

**Comment by rushilsrivastava** [comment]
Kinda disappointed this was missing from the launch. The models are fun to play with, but the API and client as a whole has been frustrating to work with.

**Comment by abdulqkhan** [comment]
The API needs to have a way to return valid JSON otherwise its a waste of time.

**Comment by ekhmoi** [comment]
Why Is this even offered as a part of firebase solution, when I can't even get back a guaranteed valid JSON response?

**Comment by twilsonco** [comment]
I agree it would be great to support the `response_format` tag of the OpenAI schema, including [JSON mode](https://platform.openai.com/docs/guides/text-generation/json-mode).

**Comment by hetvi01** [comment]
I'm also looking for a valid JSON format with Python SDK for chat history, if the feature still does not exist do we have any workaround to achieve the same?

**Comment by Lord-Haji** [comment]
@hetvi01 I was initially just using regex to fix whenever we had invalid JSONs but it kept giving more and more weird jsons so I'm just using gpt 3.5's json mode to fix the data as a fallback. You can use any of the local LLMs to achieve the same might be cheaper

**Comment by joshdaloewen** [comment]
I've tried feeding the invalid JSON back into a follow-up query asking basically "fix this invalid JSON".  Sometimes it works, sometimes it gives back different, but still invalid, JSON.  I'm surprised how badly the Gemini API behaves, especially as I'm trying to use it side-by-side with OpenAI api calls, and it just won't behave predictably.

**Comment by abdulqkhan** [comment]
right now the cleanest way is to strip the unwanted characters, literals and turn it into a valid JSON. I've even had to use dynamic properties because Gemini doesn't use consistent names for the objects returned, even when you specify to use an object name in the response

**Comment by Lord-Haji** [comment]
> right now the cleanest way is to strip the unwanted characters, literals and turn it into a valid JSON. I've even had to use dynamic properties because Gemini doesn't use consistent names for the objects returned, even when you specify to use an object name in the response

@abdulqkhan  this would be the case if they only added unwanted characters. Sometimes they return a response with single quotes ``'`` sometimes ``"`` double quotes inside a value isn't escaped. There are missing ``,``s at times properties aren't delimited with ``,``s. I am not sure if you have tested it enough. But unwanted characters isn't the only issue right now.

**Comment by abdulqkhan** [comment]
I have done a lot of testing, and have a few production apps deployed that are working fine with the manual stripping and parsing of the responses, ... are you providing a sample expected response along with your prompt?

**Comment by Lord-Haji** [comment]
Ofcourse I am. It hasn't broken for you probably because of the type of
content you are sending to the API. Its also running fine for me about 80%
of the times and failing for 20% for the same prompts with different content

**Comment by avastmick** [comment]
Bumping this up. Does anyone know if there is a formal feature request for the API on this? 

Right now, it's a deal breaker as the JSON generation, including all manner of back flips to handle variously stripping out markdown artefacts (as noted above) and control characters (\u0000-\u001F). The actual JSON produced by Gemini is highly unreliable. This limits real-world usage for anything of any complexity.

**Comment by MarkDaoust** [comment]
The function_calling feature is the best way to do this. It lets you strictly describe the schema, and returns the data structure, not text you have to parse.   

https://ai.google.dev/tutorials/structured_data_extraction

It doesn't use constrained decoding yet, so you can still get errors, but it's pretty good in my experience.

**Comment by balewgize** [comment]
Sadly, this is an important feature still missing. I tried to clean the response manually but it seems there are a lot of cases.

@abdulqkhan could you share the code that is working for you? if possible.

**Comment by MarkDaoust** [comment]
This feature has been added to the API.
You can use it through REST right now.

We're working on the new release to include it, once 0.6.2 of google-ai-generativelanguage is out, we can merge https://github.com/google/generative-ai-python/pull/274 and make a new release.

**Comment by balewgize** [comment]
Thanks for the update! @MarkDaoust

**Comment by dhruvkb** [comment]
Making a request like this

```python
genai.GenerativeModel("gemini-pro").generate_content(
    self.prompt,                                          
    generation_config=GenerationConfig(response_mime_type="application/json")
)
```

now returns a 400 response like this

```
    @functools.wraps(callable_)
    def error_remapped_callable(*args, **kwargs):
        try:
            return callable_(*args, **kwargs)
        except grpc.RpcError as exc:
>           raise exceptions.from_grpc_error(exc) from exc
E           google.api_core.exceptions.InvalidArgument: 400 Json mode is not enabled for models/gemini-pro

../../../../.venv/lib/python3.12/site-packages/google/api_core/grpc_helpers.py:78: InvalidArgument
```

**Comment by MarkDaoust** [comment]
@dhruvkb > 400 Json mode is not enabled for models/gemini-pro

Not all odels support this setting try `models/gemini-1.5-pro-latest`.

**Comment by ambroser53** [comment]
As I recently put in [this issue](https://github.com/googleapis/python-aiplatform/pull/3639#issuecomment-2088817363), JSON mode seems to have broken.

**Comment by Praj-17** [comment]
Hi, Is this done I am still struggling to get consistent Json

**Comment by Suzzit6** [comment]
same the json output is still incosistent

**Comment by MarkDaoust** [comment]
Yes this should be working now. 

See "Generate JSON from schema" in this example: https://github.com/google-gemini/cookbook/blob/674daad4057ff8c747417cb75bc4f91aed6324b8/quickstarts/JSON_mode.ipynb#Generate-JSON-from-schema

`response_mime_type` is just a suggestion, but setting a `schema` like this example activates constrained decoding, and should strictly follow the provided schema.
