### ISSUE TITLE
AttributeError: module 'google.generativeai' has no attribute 'generate_content'

### ISSUE THREAD

**Issue by VAMSINADH2000** [google/generative-ai-python#146]
### Description of the bug:

I ran in to this Error
AttributeError: module 'google.generativeai' has no attribute 'generate_content'

import os
import google.generativeai as genai
genai.configure(api_key=os.getenv('GEMINI_API_KEY'))

prompt = "Write a story about a magic backpack."

response = genai.generate_content(
    model="gemini-pro",
    prompt=prompt
)

### Any other information you'd like to share?

Python 3.9.0
google-generativeai==0.3.2

**Comment by Hamza-nabil** [comment]
You need to load the model first using `genai.GenerativeModel`:

```python
import os
import google.generativeai as genai

genai.configure(api_key=os.getenv('GEMINI_API_KEY'))

model = genai.GenerativeModel('gemini-pro')

prompt = "Write a story about a magic backpack."
response = model.generate_content(prompt)

print(response.text) 
```

check the [README](https://github.com/google/generative-ai-python/blob/main/README.md)  and [Gemini API: Quickstart with Python](https://ai.google.dev/tutorials/python_quickstart)

**Comment by MarkDaoust** [comment]
Yes, @Hamza-nabil is right. did that code come from one of our samples or something?

**Comment by MarkDaoust** [comment]
Oh, the bad example is from here:

https://ai.google.dev/docs/gemini_api_overview.md

I'll fix it, one second.
