### ISSUE TITLE
Set a role for GenerativeModel (gemini-pro) with Python SDK?

### ISSUE THREAD

**Issue by wired88** [google/generative-ai-python#148]
### Description of the feature request:

Hey is there rly no chance to set a role for the gemini pro model when using the python SDK? I tried to edit the Role in the source code but then my request will be allways blocked. 
Also checked the docs from gemini API and vertex but dant find anything -> play around also not keeping me to the goal. 

### What problem are you trying to solve with this feature?

To set a role for gemini using the vertex lib (GenerativeModel("gemini-pro"))

**Comment by MarkDaoust** [comment]
This is working as intended. 

Right now the only `roles` the API recognizes are `user` and `model`. Anything else is an error. 

I believe the API team is planning to support system-instructions soon, but I have no details on how.
