### ISSUE TITLE
Bug with Arabic context

### ISSUE THREAD

**Issue by eta1232002** [google/generative-ai-python#161]
### Description of the bug:

On Colab, when I use Langchain and Gemini API with "only Arabic" pdf file, I got the following error. But it works well with English pdf files.

"ERROR:tornado.access:500 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 10208.52ms

WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised InternalServerError: 500 POST http://localhost:38813/v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint: An internal error has occurred. Please retry or report in https://developers.generativeai.google/guide/troubleshooting."

### Actual vs expected behavior:

Actual behavior:

ERROR:tornado.access:500 POST /v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 10208.52ms
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised InternalServerError: 500 POST http://localhost:38813/v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint: An internal error has occurred. Please retry or report in https://developers.generativeai.google/guide/troubleshooting.

**Comment by Hamza-nabil** [comment]
@eta1232002 it would be better if you provide a minimal example to reproduce the error.
