### ISSUE TITLE
Passing tools in send_message instead of initializing the GenerativeModel 

### ISSUE THREAD

**Issue by liqul** [google/generative-ai-python#181]
### Description of the feature request:

Currently, we can only pass the list of tools when initializing the GenerativeModel, e.g.,

```python
model = genai.GenerativeModel(
    'gemini-pro',
    tools=[datetime])
```

However, this is very inconvenient and is different from OpenAI's API where the tools are passed when generating content. The current design makes it impossible to dynamically change the `tools` argument. For example, some of my calls do not need to pass the tools and I only want text response; sometimes, I also need to change the list of tools for different tasks. 

I'm looking for the API design like the following:
```python
chat = model.start_chat()

response = chat.send_message(
    'How many days until Christmas',
    tools =[datetime],
)
```

**Comment by MarkDaoust** [comment]
Fixed in #201
