### ISSUE TITLE
How to interpret "safety_feedback"

### ISSUE THREAD

**Issue by nitaidean** [google/generative-ai-python#21]
Hi, I am getting this error upon trying to use genai.generate_text()

```
Completion(
    candidates=[], 
    result=None, 
    filters=[{'reason': <BlockedReason.SAFETY: 1>}], 
    safety_feedback=[{
        'rating': {'category': <HarmCategory.HARM_CATEGORY_TOXICITY: 2>, 'probability': <HarmProbability.LOW: 2>},
        'setting': {'category': <HarmCategory.HARM_CATEGORY_TOXICITY: 2>, 'threshold': <HarmBlockThreshold.BLOCK_LOW_AND_ABOVE: 1>}}])
```

Nothing in my prompt is in the least bit toxic, it's just frontend code. Can you please tell me what input args to give to generate_text so it stops blocking? I tried to mess with safety_settings but it's not well documented and I didn't succeed.

**Comment by MarkDaoust** [comment]
`filters=[{'reason': <BlockedReason.SAFETY: 1>}],` tells you this is something you can control with the safety settings.
And the `safety_feedback` tells you that it evaluated the toxcicity probability as low, and that your setting it to block low and above.

You can control this with the `safety_settings`  argument to `generate_text`: https://developers.generativeai.google/api/python/google/generativeai/generate_text

```
safety_settings = [{'category':palm.types.HarmCategoty.HARM_CATEGORY_TOXICITY,
                                 'threshold':palm.types.HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE}]
```

That's not pretty.

I should: 

- Update the function to accept a dict as the safety settings and update the safety settings to handle simple strings. so this works: `safety_settings={'toxicity':'medium'}`
- Fix the docs tools to cross-link better (there's no easy way to find `HarmCategory` and `HarmBlockThreshold` from `generate_text`)

**Comment by soosung80** [comment]
I'll also work on the safety settings doc to better explain and link to the API docs. I think adding an example of adjusting the settings would have helped here.

**Comment by sleeepeer** [comment]
I used these lines but still got similar results:
```python
completion = palm.generate_text(
    model=model,
    prompt=prompt,
    temperature=0,
    # The maximum length of the response
    max_output_tokens=2048,
    safety_settings=[
        {
            "category": palm.types.HarmCategory.HARM_CATEGORY_DEROGATORY,
            "threshold": palm.types.HarmBlockThreshold.BLOCK_NONE,
        },
        {
            "category": palm.types.HarmCategory.HARM_CATEGORY_TOXICITY,
            "threshold": palm.types.HarmBlockThreshold.BLOCK_NONE,
        },        
        {
            "category": palm.types.HarmCategory.HARM_CATEGORY_VIOLENCE,
            "threshold": palm.types.HarmBlockThreshold.BLOCK_NONE,
        },        
        {
            "category": palm.types.HarmCategory.HARM_CATEGORY_SEXUAL,
            "threshold": palm.types.HarmBlockThreshold.BLOCK_NONE,
        },        
        {
            "category": palm.types.HarmCategory.HARM_CATEGORY_MEDICAL,
            "threshold": palm.types.HarmBlockThreshold.BLOCK_NONE,
        },        
        {
            "category": palm.types.HarmCategory.HARM_CATEGORY_DANGEROUS,
            "threshold": palm.types.HarmBlockThreshold.BLOCK_NONE,
        },
    ],
    # stop_sequences="\n"
)
```

```
Completion(candidates=[], 
    result=None, 
    filters=[{'reason': <BlockedReason.SAFETY: 1>}], 
    safety_feedback=[{'
        rating': {'category': <HarmCategory.HARM_CATEGORY_TOXICITY: 2>, 'probability': <HarmProbability.MEDIUM: 3>}, 
        'setting': {'category': <HarmCategory.HARM_CATEGORY_TOXICITY: 2>, 'threshold': 
        <HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE: 2>}
}])
```

I tried ‘BLOCK_ONLY_HIGH’ and other thresholds but got the same safety_feedback above.

**Comment by MarkDaoust** [comment]
> I tried ‘BLOCK_ONLY_HIGH’ and other thresholds but got the same safety_feedback above.

Strange. The safety_feedback in the output says  it's set to medium. 

Trying things in colab, it seems to be working correctly.  Can you share a colab to reproduce this?

**Comment by Uncover-F** [comment]
Same for me
