### ISSUE TITLE
Add an image to use models/gemini-pro-vision, or switch your model to a text model.

### ISSUE THREAD

**Issue by jun0wanan** [google/generative-ai-python#210]
### Description of the bug:

When I use the model gemini-vision-pro, I only give it the text . I will give me that bug. How can I solve it ?

**Comment by markmcd** [comment]
If you want to use text, use `gemini-pro`. If you want to use images, using `gemini-pro-vision`. You are free to switch between them as necessary.

**Comment by wuhongsheng** [comment]
+1
