### ISSUE TITLE
Imposter library: google-generativeai-gen

### ISSUE THREAD

**Issue by LindaLawton** [google/generative-ai-python#218]
### Description of the bug:

there are two libraries 
- [pip install google-generativeai](https://pypi.org/project/google-generativeai/)
- [pip install google-generativeai-gen](https://pypi.org/project/google-generativeai-gen/)
They both appear to point back here

the first was built in December the second was built in February

Which one should we be using

The code for Chat example works with the first one and results in an error in the second one

> Traceback (most recent call last):
>   File "C:\Development\FreeLance\Gemini\ChatBot\main.py", line 96, in <module>
>     asyncio.run(main())
>   File "C:\Users\linda\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "C:\Users\linda\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
>     return future.result()
>   File "C:\Development\FreeLance\Gemini\ChatBot\main.py", line 66, in main
>     convo.send_message(user_input)
>   File "C:\Development\FreeLance\GoogleSamples\Python\google-api-python-samles\ChatBot\.venv\lib\site-packages\google\generativeai\generative_models.py", line 366, in send_message
>     response = self.model.generate_content(
>   File "C:\Development\FreeLance\GoogleSamples\Python\google-api-python-samles\ChatBot\.venv\lib\site-packages\google\generativeai\generative_models.py", line 235, in generate_content
>     request = self._prepare_request(
>   File "C:\Development\FreeLance\GoogleSamples\Python\google-api-python-samles\ChatBot\.venv\lib\site-packages\google\generativeai\generative_models.py", line 216, in _prepare_request
>     return glm.GenerateContentRequest(
>   File "C:\Development\FreeLance\GoogleSamples\Python\google-api-python-samles\ChatBot\.venv\lib\site-packages\proto\message.py", line 615, in __init__
>     super().__setattr__("_pb", self._meta.pb(**params))
> TypeError: Parameter to MergeFrom() must be instance of same class: expected <class 'Content'> got <class 'str'>.
> 

### Actual vs expected behavior:

I would expect that there be a single pip package built by this libray and that it work with the sample code given on the page

### Any other information you'd like to share?

the sample code given on the page for the second library appears to say to use the first library which is quite confusing.

**Comment by MarkDaoust** [comment]
Hi, thanks for reporting this. 

[pip install google-generativeai](https://pypi.org/project/google-generativeai/) is us.

 [pip install google-generativeai-gen](https://pypi.org/project/google-generativeai-gen/) is **not us**. 
 We're trying to figure out what we should do about that.

**Comment by singhniraj08** [comment]
@LindaLawton, 
[pip install google-generativeai-gen](https://pypi.org/project/google-generativeai-gen/) library is removed and you can keep using [pip install google-generativeai](https://pypi.org/project/google-generativeai/) package. Thank you for reporting this to us. Since this issue is resolved for you, requesting you to close this issue.

**Comment by markmcd** [comment]
Thanks for the report Linda - the author was cooperative and removed both the PyPI package and updated their README to make it clear it's different.

The code itself was innocuous - there was nothing malicious going on, just a custom package that used a similar name.
