### ISSUE TITLE
How to Insert Images at Specific Positions Within Text in Gemini pro vision?

### ISSUE THREAD

**Issue by tangyipeng100** [google/generative-ai-python#220]
### Description of the bug:

I am working with Gemini pro vision and am looking to implement a feature where an image can be inserted at a specific position within the text, not just at the beginning or end like in the Google studio. As shown in the attached image, the picture is embedded in the middle of the text. Could anyone suggest APIs that enable this effect? Are there any code examples or libraries that I could refer to for this purpose?
The current api can just insert img as；
```
response = multimodal_model.generate_content(
                [_prompt, jpeg_image],
    )
```
![image](https://github.com/google/generative-ai-python/assets/45865043/89c6a315-6ba9-404e-a647-d2a38a79defe)

**Comment by MarkDaoust** [comment]
```
response = multimodal_model.generate_content(
                [_prompt, jpeg_image],
)
```


Hi, the API already handles this case. A single turn takes a list of parts. A part can be text or an image. 

```
prompt = ['before', image1, 'middle', image2, 'after']
response = multimodal_model.generate_content(prompt)
```

Should work, let us know if there's a more specific problem.
