### ISSUE TITLE
Function calling example.

### ISSUE THREAD

**Issue by LindaLawton** [google/generative-ai-python#226]
### Description of the feature request:

I am trying to use [function calling](https://ai.google.dev/docs/function_calling#expandable-3)  Do we have a working example

Currently I'm building stuff manually and its a pain

```
def build_function_tool_single(name, description, properties, required):
    return {
        "function_declarations": [{
            "name": name,
            "description": description,
            "parameters": {
                "type_": "OBJECT",  # Indicates that parameters are structured as an object
                "properties": properties,  # List of property dictionaries
                "required": required  # List of required property names
            }
        }]
    }
```

### What problem are you trying to solve with this feature?

Figuring out function calling with the library.  how to build a tool properly.

### Any other information you'd like to share?

I am seeing some code here [content_types.py#L423](https://github.com/google/generative-ai-python/blob/69cb0ea674e54c6e62db5e60ea44e19d4336a1ae/google/generativeai/types/content_types.py#L423) i am wondering if i am on the right track

**Comment by san425** [comment]
There's a python quickstart at [https://ai.google.dev/tutorials/function_calling_python_quickstart](https://ai.google.dev/tutorials/function_calling_python_quickstart)

In it, there's an example of how to implement function calling with a simple calculator function :)

**Comment by LindaLawton** [comment]
Here i thought I had already looked everywere thank you!
