### ISSUE TITLE
Google Gemini 1.5 pro via API access

### ISSUE THREAD

**Issue by haseeb-heaven** [google/generative-ai-python#227]
### Description of the feature request:

I want to use latest version of Google **Gemini-1.5-pro** via API or SDK that can be integrated to our projects.

### What problem are you trying to solve with this feature?

Solving the whole codebase upload media and more with 1 Million tokens limit to achieve maximum efficiency from this model.

### Any other information you'd like to share?

Here is error i got 

```bash
Error generating response: 404 models/gemini-1.5-pro-latest is not found for API version v1beta, or is not supported for GenerateContent. Call ListModels to see the list of available models and their supported methods.
```

Here is the code:

```python
import os
import google.generativeai as genai
from dotenv import load_dotenv

def init_api_keys():
    try:
        load_dotenv()
        api_key = os.getenv("GEMINI_API_KEY")
        genai.configure(api_key=api_key)
    except Exception as exception:
        print("Error in initializing API keys:", exception)
        raise

def generate_response(prompt:str):

  # Set up the model
  generation_config = {
    "temperature": 0.1,
    "top_p": 1,
    "top_k": 1,
    "max_output_tokens": 2048,
  }
  
  model = genai.GenerativeModel(model_name="gemini-1.5-pro-latest",generation_config=generation_config)
  
  prompt_parts = [prompt]
  
  try:
    response = model.generate_content(prompt_parts)
    print(response.text)
  except Exception as exception:
    print("Error generating response:", exception)
    
if __name__ == "__main__":
    init_api_keys()
    prompt = input("> ")
    generate_response(prompt)
```

**Comment by LindaLawton** [comment]
First you need to be white listed for Google Gemini-1.5-pro
If you are then you should know that Google Gemini-1.5-pro doesnt work though the gemini api which is what this library is for.

If you do have access and really want to try Google Gemini-1.5-pro try going though vertex and use the vertex library i hear it works there.

**Comment by haseeb-heaven** [comment]
> First you need to be white listed for Google Gemini-1.5-pro If you are then you should know that Google Gemini-1.5-pro doesnt work though the gemini api which is what this library is for.
> 
> If you do have access and really want to try Google Gemini-1.5-pro try going though vertex and use the vertex library i hear it works there.

But still in vertex-ai Gemini 1.5 pro is not available via API?

**Comment by LindaLawton** [comment]
@haseeb-heaven That's a completely different white list.  I have only heard that it exits i don't know anyone that got access to that yet.  Its not the same as the white list to access it in Google Ai Studio.

Im not even sure how to get on that whitelist.

**Comment by SeanTolstoyevski** [comment]
I can see version 1.5 in ai studio, I can selected this version. And when I examine the network panel after the prompt sending and receive response, requests are sent to google services with the 1.5 version parameter. However, when I try to access the 1.5 version via the API, I get 404, which is the error our friend received.

I think even though we are whitelisted, this does not mean that we can access the API.
Maalesef Google kaynaklarında bununla ilgili yeterince döküman yok.

**Comment by haseeb-heaven** [comment]
> @haseeb-heaven That's a completely different white list. I have only heard that it exits i don't know anyone that got access to that yet. Its not the same as the white list to access it in Google Ai Studio.
> 
> Im not even sure how to get on the Vertex ai whitelist for gemini pro 1.5
> 
> You need to test via ai studio.

Okay i will test via Vertex AI API but i prefer Google AI Studio API because it need only single API key for authorization.

**Comment by LindaLawton** [comment]
@SeanTolstoyevski I think you need to reread what you are white Listed for

There is NO api currently for Gemini pro 1.5 the white list only gives you access to test in Google ai studio they haven't implemented an API for it they just gave us ai studio testing

**Comment by flexchar** [comment]
I've got whitelisted on AI Studio too. Shame it's blocked in Denmark (or whole EU in that regard). If someone reverse-engineers, it feels like GPT-5 for some tasks and I am excited to integrate. 

@LindaLawton do you have any idea where to find application/form for use in VertexAI?

**Comment by OlegRuban-ai** [comment]
I have access to 1.5 in AIStudio, but there is no API access in version 0.4.1. Does anyone know when they plan to add it? The following packages are currently available:

models/chat-bison-001
models/text-bison-001
models/embedding-gecko-001
models/gemini-1.0-pro
models/gemini-1.0-pro-001
models/gemini-1.0-pro-latest
models/gemini-1.0-pro-vision-latest
models/gemini-pro
models/gemini-pro-vision
models/embedding-001
models/aqa

**Comment by LindaLawton** [comment]
I got access today it's comming.

**Comment by Arkm20** [comment]
Same here

**Comment by davidogbonnaeze** [comment]
@LindaLawton @Arkm20 , please how did you get access. i need it

**Comment by LindaLawton** [comment]
Im a google developer expert for ai/ml some on at google sent me a hangout message and asked for the project i wanted white listed.    If GDE's are getting access its only a matter of time before the others white listed for 1.5 on ai studio get access hang in there. 

Heads up the model name is gemini-1.5-pro-latest when you get access.

**Comment by davidogbonnaeze** [comment]
Thank you @LindaLawton

**Comment by manbeardave** [comment]
@LindaLawton are you leveraging pro-1.5 in the python SDK? or in the console?

**Comment by LindaLawton** [comment]
Im using this library to work with Gemini pro 1.5  the code is the same its just a different model.  You use gemini-1.5-pro-latest instead of gemini-pro and your good to go.

you need to be whitelisted.

**Comment by haseeb-heaven** [comment]
> Im using this library to work with Gemini pro 1.5 the code is the same its just a different model. You use gemini-1.5-pro-latest instead of gemini-pro and your good to go.
> 
> you need to be whitelisted.

But how to get whitelisted please explain that in details thanks

**Comment by LindaLawton** [comment]
If you are white Listed for ai studio you will get in eventually

If you're not you need to apply to be white Listed

In both cases you just wait

**Comment by haseeb-heaven** [comment]
> If you are white Listed for ai studio you will get in eventually
> 
> If you're not you need to apply to be white Listed
> 
> In both cases you just wait

I tried to list all the models available and i got this list.

```python
def list_all_models():
    try:
        models = genai.list_models()
        for model in models:
            print(f"Name: {model.name}, Display Name: {model.display_name}")
    except Exception as exception:
        print("Error listing models:", exception)
```

Output:

```bash
Name: models/chat-bison-001, Display Name: PaLM 2 Chat (Legacy)
Name: models/text-bison-001, Display Name: PaLM 2 (Legacy)
Name: models/embedding-gecko-001, Display Name: Embedding Gecko
Name: models/gemini-1.0-pro, Display Name: Gemini 1.0 Pro
Name: models/gemini-1.0-pro-001, Display Name: Gemini 1.0 Pro 001 (Tuning)
Name: models/gemini-1.0-pro-latest, Display Name: Gemini 1.0 Pro Latest
Name: models/gemini-1.0-pro-vision-latest, Display Name: Gemini 1.0 Pro Vision
Name: models/gemini-pro, Display Name: Gemini 1.0 Pro
Name: models/gemini-pro-vision, Display Name: Gemini 1.0 Pro Vision
Name: models/embedding-001, Display Name: Embedding 001
Name: models/aqa, Display Name: Model that performs Attributed Question Answering.
Name: models/chat-bison-001, Display Name: PaLM 2 Chat (Legacy)
Name: models/text-bison-001, Display Name: PaLM 2 (Legacy)
Name: models/embedding-gecko-001, Display Name: Embedding Gecko
Name: models/gemini-1.0-pro, Display Name: Gemini 1.0 Pro
Name: models/gemini-1.0-pro-001, Display Name: Gemini 1.0 Pro 001 (Tuning)
Name: models/gemini-1.0-pro-latest, Display Name: Gemini 1.0 Pro Latest
Name: models/gemini-1.0-pro-vision-latest, Display Name: Gemini 1.0 Pro Vision
Name: models/gemini-pro, Display Name: Gemini 1.0 Pro
Name: models/gemini-pro-vision, Display Name: Gemini 1.0 Pro Vision
Name: models/embedding-001, Display Name: Embedding 001
Name: models/aqa, Display Name: Model that performs Attributed Question Answering.
```

My Google generativeai version:
```bash
pip show google-generativeai
Name: google-generativeai
Version: 0.4.1
```

See the `gemini-1.5-pro-latest` isn't even listed.

**Comment by LindaLawton** [comment]
It will be when they give you access I had to have my project whitelist

**Comment by danh-conduit** [comment]
I too get the same result (404) and the same (non-1.5) list of models as everyone else except @LindaLawton, using google-generativeai v 0.4.1. I have AI Studio 1.5 access via both a personal account and a Google Workspace account. I generated API keys from both those accounts but neither of them yields gemini-1.5-pro-latest. Google, please show us the love 🙏

**Comment by LindaLawton** [comment]
I can not you must wait to be white Listed to the API it's comming they are releasing it slowly

**Comment by MarkDaoust** [comment]
It looks like they've removed the whitelist and opened up access to 1.5 in AI Studio. Hopefully that means it will be accessible in the API soon.

**Comment by haseeb-heaven** [comment]
> It looks like they've removed the whitelist and opened up access to 1.5 in AI Studio. Hopefully that means it will be accessible in the API soon.

Yes i saw Twitter post about this hopefully we will get the API access soon.

**Comment by davidogbonnaeze** [comment]
https://twitter.com/JeffDean/status/1770653917543870571

**Comment by SomebodySysop** [comment]
Any idea if the pricing for Gemini Pro 1.5 will be the same as 1.0?

https://ai.google.dev/pricing

**Comment by shuimu5418** [comment]
Gemini 1.5 pro api is avaliable now.

**Comment by LET19** [comment]
> Gemini 1.5 pro api is avaliable now.

sry friend, how do you get it?
I checked my google dev studio, its "code" button still unavailable. and it's not listed in model list api either.
![image](https://github.com/google/generative-ai-python/assets/33142139/c63095b1-ae45-4884-b599-f0a65be84ecf)

**Comment by shuimu5418** [comment]
> > Gemini 1.5 pro api is avaliable now.
> 
> sry friend, how do you get it? I checked my google dev studio, its "code" button still unavailable. and it's not listed in model list api either. ![image](https://private-user-images.githubusercontent.com/33142139/316769974-c63095b1-ae45-4884-b599-f0a65be84ecf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NDM2ODYsIm5iZiI6MTcxMTQ0MzM4NiwicGF0aCI6Ii8zMzE0MjEzOS8zMTY3Njk5NzQtYzYzMDk1YjEtYWU0NS00ODg0LWI1OTktZjBhNjViZTg0ZWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDA4NTYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyYWFmMmY3ZTNlMWE0MDk5NzdiNTE1ZjRkODAyYWZlMjI5N2QzM2EyYmE4NmQ0ODhkZDFiMjA1Mzk1NzkxNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M9U5P5_Z1Ip6FSXllKbmtKgPi3rARy0nURcj3CAQjJI)

i got an email....
```
[Preview] Gemini API Access External
Hello,
We're thrilled to announce that we’ve started rolling out access to the Gemini 1.5 Pro API! This lets you bring the power of Gemini 1.5 Pro beyond Google AI Studio.
```
so i got it.

**Comment by LET19** [comment]
> > > Gemini 1.5 pro api is avaliable now.
> > 
> > 
> > sry friend, how do you get it? I checked my google dev studio, its "code" button still unavailable. and it's not listed in model list api either. ![image](https://private-user-images.githubusercontent.com/33142139/316769974-c63095b1-ae45-4884-b599-f0a65be84ecf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NDM2ODYsIm5iZiI6MTcxMTQ0MzM4NiwicGF0aCI6Ii8zMzE0MjEzOS8zMTY3Njk5NzQtYzYzMDk1YjEtYWU0NS00ODg0LWI1OTktZjBhNjViZTg0ZWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDA4NTYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyYWFmMmY3ZTNlMWE0MDk5NzdiNTE1ZjRkODAyYWZlMjI5N2QzM2EyYmE4NmQ0ODhkZDFiMjA1Mzk1NzkxNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M9U5P5_Z1Ip6FSXllKbmtKgPi3rARy0nURcj3CAQjJI)
> 
> i got an email....
> 
> ```
> [Preview] Gemini API Access External
> Hello,
> We're thrilled to announce that we’ve started rolling out access to the Gemini 1.5 Pro API! This lets you bring the power of Gemini 1.5 Pro beyond Google AI Studio.
> ```
> 
> so i got it.

ok. thx. maybe what I can do is just waiting.

**Comment by formvoltron** [comment]
> > so i got it.
Did you need to ask for it?  Or are they just handing it out to everyone on the gemini 1.5 early access list?

**Comment by ReEnMikki** [comment]
I am also curious how to ask or apply to get access to Gemini 1.5 Pro API. I have already sent the application to get early access to it weeks ago, but they never responded. Anyone who knows please help!

**Comment by Experilous** [comment]
i got access through mail but getting error in trying to access 
![image](https://github.com/google/generative-ai-python/assets/125695829/f2eafa5b-6636-43db-8bb2-ba24dabe69df)

**Comment by LET19** [comment]
> i got access through mail but getting error in trying to access ![image](https://private-user-images.githubusercontent.com/125695829/317157911-f2eafa5b-6636-43db-8bb2-ba24dabe69df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MjM0MzIsIm5iZiI6MTcxMTUyMzEzMiwicGF0aCI6Ii8xMjU2OTU4MjkvMzE3MTU3OTExLWYyZWFmYTViLTY2MzYtNDNkYi04YmIyLWJhMjRkYWJlNjlkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QwNzA1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jN2NmZmNjNzUxYzEzNGRlYmM0MTQ1MjBlYmZmYjM2NzI5Y2I4NjJhNzQwYmUyNjhhY2Y5ZTQ3NzMwN2NlZTMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LSJH5JIZv2oYoqTn2tBXCYe0yCbuIEczUHjNWgjJ5oI)

did u tried with created a new key?

**Comment by Experilous** [comment]
> > i got access through mail but getting error in trying to access ![image](https://private-user-images.githubusercontent.com/125695829/317157911-f2eafa5b-6636-43db-8bb2-ba24dabe69df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MjM0MzIsIm5iZiI6MTcxMTUyMzEzMiwicGF0aCI6Ii8xMjU2OTU4MjkvMzE3MTU3OTExLWYyZWFmYTViLTY2MzYtNDNkYi04YmIyLWJhMjRkYWJlNjlkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QwNzA1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jN2NmZmNjNzUxYzEzNGRlYmM0MTQ1MjBlYmZmYjM2NzI5Y2I4NjJhNzQwYmUyNjhhY2Y5ZTQ3NzMwN2NlZTMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LSJH5JIZv2oYoqTn2tBXCYe0yCbuIEczUHjNWgjJ5oI)
> 
> did u tried with created a new key?

yes I tried with new key in google ai studio also and tried with private key of project also , same error

**Comment by ReEnMikki** [comment]
> i got access through mail but getting error in trying to access ![image](https://private-user-images.githubusercontent.com/125695829/317157911-f2eafa5b-6636-43db-8bb2-ba24dabe69df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MjUzOTQsIm5iZiI6MTcxMTUyNTA5NCwicGF0aCI6Ii8xMjU2OTU4MjkvMzE3MTU3OTExLWYyZWFmYTViLTY2MzYtNDNkYi04YmIyLWJhMjRkYWJlNjlkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QwNzM4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NGMzYWJhMjgzMGJhZWU0YzAzYTUxMTQ1OTVmYThkYjNhZGJhN2JiZWRlNDAzM2ZkNDQ5MjcwMzM2YjcxN2ZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FjEWpcY9eL37g14-Zknh2qftkrt-MugkhFar_aOibzU)

So how did you get access to begin with ? Is it because you already had access to Gemini 1.5 Pro waitlist before they removed the waitlist ? Is it because you have a Google Workspace account ?

**Comment by ReEnMikki** [comment]
Searching through internet I only saw some pages or some people saying Google rolled out Gemini 1.5 Pro API to "some developers", but regarding how is this process decided, like how do they decide who to give access to - no one said anything to clarify. Wtf.

**Comment by LindaLawton** [comment]
Most of these questions are out of scope for this library I recommend you join [discord channel 
- gemini-api](https://ai.google.dev/docs/discord)
You can get help there from other developers

**Comment by goodanthony** [comment]
Hope this helps

Firstly Google would send you an invite to join. Then fill that form and you have to specify your project id. Make sure you remember the project id!

First email from Google
Hello,
We're thrilled to announce that we've started rolling out access to the Gemini 1.5 Pro API! This lets you bring the power of Gemini 1.5 Pro beyond Google AI Studio.
How to request access:
Submit one Google Cloud Project Number (digits only) using this form.
We'll email you if access is enabled for your project.
Gemini 1.5 Pro:

Fill form

Reply from Google:
Hello,
We're excited to share that you now have access to the Gemini 1.5 Pro API and the File API! Your feedback on this highly-requested preview feature is incredibly valuable. Please share your thoughts and any projects you build!
Instructions:

Go to https://aistudio.google.com and create a new key with the "Project ID" that you filled in the form (I had to create a new key. If you already have a key with that project ID, I assume it would work).

Then run the following command:

curl \
  -H 'Content-Type: application/json' \
  -d '{"contents":[{"parts":[{"text":"Write a story about Wikipedia"}]}]}' \
  -X POST 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-latest:generateContent?key=yourkey

The mistake I made was using a key from a different project.

**Comment by haseeb-heaven** [comment]
Thanks all for confirming i am yet to receive my API key from Google once i receive i will update this issue.

**Comment by Arkm20** [comment]
So it looks like the Gemini 1.5 rates isn't the same... Sad...

Rate limit	2 queries per minute, 1000 queries per day

according to Official Gemini Docs

**Comment by Arkm20** [comment]
@goodanthony I still haven't recieved that reply...

**Comment by haseeb-heaven** [comment]
The API for **Google Gen AI 1.5** is now available.
https://developers.googleblog.com/2024/04/gemini-15-pro-in-public-preview-with-new-features.html?m=1

**Comment by johnomeara1** [comment]
> The API for **Google Gen AI 1.5** is now available. https://developers.googleblog.com/2024/04/gemini-15-pro-in-public-preview-with-new-features.html?m=1

Still not working for me... unless I am doing something wrong?

> GoogleGenerativeAIError: [404 Not Found] models/gemini-1.5-pro-latest is not found for API version v1, or is not supported for GenerateContent. Call ListModels to see the list of available models and their supported methods.

The code that generated the above error works perfectly fine with the model code `gemini-pro`, but not with `gemini-1.5-pro-latest`

¯\_(ツ)_/¯

**Comment by goodanthony** [comment]
@johnomeara1, try creating a new key at  https://aistudio.google.com/ with the "Project ID" that you are calling the API.

**Comment by johnomeara1** [comment]
Thanks for the tip!

Here's what ended up working for me:

```js
const model = genAI.getGenerativeModel({ model: "gemini-1.5-pro-latest" }, {
    apiVersion: 'v1beta',
});
```

The key is using API version `v1beta`, as that is the only version that supports the `gemini-1.5-pro-latest` model at this time. Although the above code is for the javascript client library, it can be modified for various languages of google's client for generative AI (python, etc.)

**Comment by zakcali** [comment]
I wish to code for golang. any chance to modifiy that code:
model := client.GenerativeModel("Gemini 1.5 Pro")
there are no curly bracets in golang version

**Comment by ewantindale** [comment]
> Thanks for the tip!
> 
> Here's what ended up working for me:
> 
> ```js
> const model = genAI.getGenerativeModel({ model: "gemini-1.5-pro-latest" }, {
>     apiVersion: 'v1beta',
> });
> ```
> 
> The key is using API version `v1beta`, as that is the only version that supports the `gemini-1.5-pro-latest` model at this time. Although the above code is for the javascript client library, it can be modified for various languages of google's client for generative AI (python, etc.)

Thanks, spent ages debugging this before I found your post. Was this communicated anywhere or were we just supposed to figure it out on our own?

**Comment by Arkm20** [comment]
It works fine for me just without the {apiversion}

**Comment by haseeb-heaven** [comment]
> > The API for **Google Gen AI 1.5** is now available. https://developers.googleblog.com/2024/04/gemini-15-pro-in-public-preview-with-new-features.html?m=1
> 
> Still not working for me... unless I am doing something wrong?
> 
> > GoogleGenerativeAIError: [404 Not Found] models/gemini-1.5-pro-latest is not found for API version v1, or is not supported for GenerateContent. Call ListModels to see the list of available models and their supported methods.
> 
> The code that generated the above error works perfectly fine with the model code `gemini-pro`, but not with `gemini-1.5-pro-latest`
> 
> ¯\_(ツ)_/¯

Create new API again and select the project which has access of Gemini 1.5 pro, it’s working for me i created new API key.

**Comment by Arkm20** [comment]
All projects have access now to Gemini 1.5 pro....  It's now on Public access. 

But I do find the rates to be very annoying. Only 2 requests per minute...

**Comment by Arkm20** [comment]
Here: https://ai.google.dev/models/gemini#:~:text=2%20queries%20per%20minute%2C%201000%20queries%20per%20day

**Comment by xuanxuanzzzii** [comment]
> ### Description of the feature request:
> I want to use latest version of Google **Gemini-1.5-pro** via API or SDK that can be integrated to our projects.
> 
> ### What problem are you trying to solve with this feature?
> Solving the whole codebase upload media and more with 1 Million tokens limit to achieve maximum efficiency from this model.
> 
> ### Any other information you'd like to share?
> Here is error i got
> 
> ```shell
> Error generating response: 404 models/gemini-1.5-pro-latest is not found for API version v1beta, or is not supported for GenerateContent. Call ListModels to see the list of available models and their supported methods.
> ```
> 
> Here is the code:
> 
> ```python
> import os
> import google.generativeai as genai
> from dotenv import load_dotenv
> 
> def init_api_keys():
>     try:
>         load_dotenv()
>         api_key = os.getenv("GEMINI_API_KEY")
>         genai.configure(api_key=api_key)
>     except Exception as exception:
>         print("Error in initializing API keys:", exception)
>         raise
> 
> def generate_response(prompt:str):
> 
>   # Set up the model
>   generation_config = {
>     "temperature": 0.1,
>     "top_p": 1,
>     "top_k": 1,
>     "max_output_tokens": 2048,
>   }
>   
>   model = genai.GenerativeModel(model_name="gemini-1.5-pro-latest",generation_config=generation_config)
>   
>   prompt_parts = [prompt]
>   
>   try:
>     response = model.generate_content(prompt_parts)
>     print(response.text)
>   except Exception as exception:
>     print("Error generating response:", exception)
>     
> if __name__ == "__main__":
>     init_api_keys()
>     prompt = input("> ")
>     generate_response(prompt)
> ```

hello,do you know how to use this api to get answers for video input

**Comment by haseeb-heaven** [comment]
> > > ### Description of the feature request:
> > > I want to use latest version of Google **Gemini-1.5-pro** via API or SDK that can be integrated to our projects.
> > > ### What problem are you trying to solve with this feature?
> > > Solving the whole codebase upload media and more with 1 Million tokens limit to achieve maximum efficiency from this model.
> > > ### Any other information you'd like to share?
> > > Here is error i got
> > > ```shell
> > > Error generating response: 404 models/gemini-1.5-pro-latest is not found for API version v1beta, or is not supported for GenerateContent. Call ListModels to see the list of available models and their supported methods.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Here is the code:
> > > ```python
> > > import os
> > > import google.generativeai as genai
> > > from dotenv import load_dotenv
> > > 
> > > def init_api_keys():
> > >     try:
> > >         load_dotenv()
> > >         api_key = os.getenv("GEMINI_API_KEY")
> > >         genai.configure(api_key=api_key)
> > >     except Exception as exception:
> > >         print("Error in initializing API keys:", exception)
> > >         raise
> > > 
> > > def generate_response(prompt:str):
> > > 
> > >   # Set up the model
> > >   generation_config = {
> > >     "temperature": 0.1,
> > >     "top_p": 1,
> > >     "top_k": 1,
> > >     "max_output_tokens": 2048,
> > >   }
> > >   
> > >   model = genai.GenerativeModel(model_name="gemini-1.5-pro-latest",generation_config=generation_config)
> > >   
> > >   prompt_parts = [prompt]
> > >   
> > >   try:
> > >     response = model.generate_content(prompt_parts)
> > >     print(response.text)
> > >   except Exception as exception:
> > >     print("Error generating response:", exception)
> > >     
> > > if __name__ == "__main__":
> > >     init_api_keys()
> > >     prompt = input("> ")
> > >     generate_response(prompt)
> > > ```
> > 
> > 
> > hello,do you know how to use this api to get answers for video input
> 
> I use the code and here is the error information: Error generating response: Timeout of 60.0s exceeded, last exception: 503 failed to connect to all addresses; last error: UNKNOWN: ipv4:142.251.42.234:443: Failed to connect to remote host: FD Shutdown

you need to see the documentation on how to send video objects with your request.

**Comment by IlayBokobza** [comment]
I have read in this stack-overflow post that you need to change to api version to beta.
https://stackoverflow.com/questions/78327178/model-not-found-when-using-gemini-1-5-when-i-have-access-to-1-5

And it seems to be supported by this page on the gemini docs.
https://ai.google.dev/gemini-api/docs/api-versions

The problem is that I have no idea how to implement this in code (dart). If any has any idea I would appreciate the help.

**Comment by ewantindale** [comment]
> I have read in this stack-overflow post that you need to change to api version to beta. https://stackoverflow.com/questions/78327178/model-not-found-when-using-gemini-1-5-when-i-have-access-to-1-5
> 
> And it seems to be supported by this page on the gemini docs. https://ai.google.dev/gemini-api/docs/api-versions
> 
> The problem is that I have no idea how to implement this in code (dart). If any has any idea I would appreciate the help.

I'm not a dart guy but looks like you need to use requestOptions: 
https://github.com/google-gemini/generative-ai-dart/blob/f3be7bbae79534535ef964e5b0fee5874aef9bdc/samples/dart/bin/function_calling.dart#L42

**Comment by IlayBokobza** [comment]
> > I have read in this stack-overflow post that you need to change to api version to beta. https://stackoverflow.com/questions/78327178/model-not-found-when-using-gemini-1-5-when-i-have-access-to-1-5
> > And it seems to be supported by this page on the gemini docs. https://ai.google.dev/gemini-api/docs/api-versions
> > The problem is that I have no idea how to implement this in code (dart). If any has any idea I would appreciate the help.
> 
> I'm not a dart guy but looks like you need to use requestOptions: https://github.com/google-gemini/generative-ai-dart/blob/f3be7bbae79534535ef964e5b0fee5874aef9bdc/samples/dart/bin/function_calling.dart#L42

Thanks man that seems to have done it
