### ISSUE TITLE
Error in response.text + Possible typo in comment in types/generation_types.py.

### ISSUE THREAD

**Issue by benchay1999** [google/generative-ai-python#234]
I am trying gemini API, and had errors when I used `response.text`, where `response=model.generate_content(f"{prompt}")`.
It outputs the following error.
"""
python3.11/site-packages/google/generativeai/types/generation_types.py", line 339, in text
    if len(parts) != 1 or "text" not in parts[0]:
                          ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'Part' is not iterable
"""
Therefore, instead of using the "quick accessor" i.e., `response.text`, I am using `response.candidates[0].content.parts[0].text` at the moment.

However, the comment in the code below seems to have omitted the "`content`".
https://github.com/google/generative-ai-python/blob/4f1ea10a0cc40ce53c142d4878f4852bb1d05d1e/google/generativeai/types/generation_types.py#L326C9-L326C77

**Comment by singhniraj08** [comment]
@benchay1999, We already have a similar issue #231 to improve `.text` accessor when the api returns nothing one way or another. Requesting you to close this issue and follow similar issue to track progress. Thank you!

**Comment by benchay1999** [comment]
Thanks for letting me know! Closing the issue now.
