### ISSUE TITLE
Clarify when to use google-generativeai vs google-cloud-aiplatform

### ISSUE THREAD

**Issue by tekumara** [google/generative-ai-python#266]
### Description of the feature request:

[google-cloud-aiplatform](https://github.com/googleapis/python-aiplatform) (ie: Vertex AI) also has the gemini and PaLM models, so its not clear to me when to use one over the other.

**Comment by singhniraj08** [comment]
@tekumara,

The Gemini API provides a programming interface for both the Gemini and PaLM [generative AI models](https://ai.google.dev/models). Gemini is Google's latest generation of generative models, and goes beyond the capabilities of the PaLM family of models. A key difference between the Gemini and PaLM models is that the Gemini vision model is able to handle image input. You can prompt Gemini models with text, or images, or both. PaLM models only handle text input and output. 
Let us know if you have further queries. Thank you!

**Comment by tekumara** [comment]
Hi I understand the differences between Gemini and PaLM, but not the when to use google-generativeai vs google-cloud-aiplatform. Any guidance would be appreciated, thank you!

**Comment by singhniraj08** [comment]
@tekumara,

If you are new to Gemini, using the [quickstarts](https://ai.google.dev/tutorials/python_quickstart) and [plans](https://ai.google.dev/pricing) for [Google AI Studio](https://ai.google.dev/tutorials/ai-studio_quickstart) is the fastest way to get started.

However, as your generative AI solutions mature, you may need a platform for building and deploying generative AI applications and solutions end to end. Google Cloud provides a comprehensive ecosystem of tools to enable developers to harness the power of generative AI, from the initial stages of app deployment to managing complex data at scale. Google Cloud's Vertex AI platform offers a suite of MLOps tools that streamline the usage, deployment, and monitoring of AI models for efficiency and reliability.

You can find more info on [Migrate to Cloud](https://ai.google.dev/docs/migrate_to_cloud) for why migrating from Gemini on Google AI to Vertex AI. Thank you!

**Comment by tekumara** [comment]
Perfect thank you!
