### ISSUE TITLE
IPv6 preventing API access

### ISSUE THREAD

**Issue by gururise** [google/generative-ai-python#29]
Using **curl** in the terminal works just fine.

```
curl \
-H 'Content-Type: application/json' \
-d '{ "prompt": { "text": "Write a story about a magic backpack"} }' \
"https://generativelanguage.googleapis.com/v1beta2/models/text-bison-001:generateText?key=<my_api_key>"
```
The above works just fine, however, when I try:

```
import google.generativeai as palm

palm.configure(api_key=<my_api_key>)
result = palm.generate_text(prompt="The opposite of hot is")
print(result)
```

Results in the following error:

```
Traceback (most recent call last):
  File "/home/gene/webhook/venv/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 72, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/gene/webhook/venv/lib/python3.10/site-packages/grpc/_channel.py", line 1030, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/gene/webhook/venv/lib/python3.10/site-packages/grpc/_channel.py", line 910, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "403:Forbidden"
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"403:Forbidden", grpc_status:14, created_time:"2023-05-25T16:47:54.953534672+00:00"}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gene/webhook/create_youtubedb.py", line 329, in <module>
    test2()
  File "/home/gene/webhook/create_youtubedb.py", line 326, in test2
    return palm.generate_text(prompt="The opposite of hot is")
  File "/home/gene/webhook/venv/lib/python3.10/site-packages/google/generativeai/text.py", line 139, in generate_text
    return _generate_response(client=client, request=request)
  File "/home/gene/webhook/venv/lib/python3.10/site-packages/google/generativeai/text.py", line 159, in _generate_response
    response = client.generate_text(request)
  File "/home/gene/webhook/venv/lib/python3.10/site-packages/google/ai/generativelanguage_v1beta2/services/text_service/client.py", line 641, in generate_text
    response = rpc(
  File "/home/gene/webhook/venv/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 113, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/gene/webhook/venv/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 74, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ServiceUnavailable: 503 403:Forbidden
```

**Comment by markmcd** [comment]
Thanks for the report.

Can you provide any more info here? I assume you ran them both from the same machine - can you confirm that? Do you have a proxy configured? (curl is more likely to be using the proxy than Python) 

Can you provide the version of the Python package you're using? And the version of Python you're using (looks like 3.10, is that right?) A `pip freeze` dump of your virtualenv would help too.

Does this happen 100% of the time, if not, what fraction? Does it work if you change the prompts so they match across REST/Py calls?

And one other thing to try - by default the Python client uses grpc, so can you try using REST in Python? And please report back if there's any difference.
```python
import google.generativeai as palm

palm.configure(api_key=..., transport="rest")
```

**Comment by yarub123** [comment]
@markmcd I tried the above with transport rest and still getting the error: 
<img width="523" alt="image" src="https://github.com/google/generative-ai-python/assets/84487964/9786141c-c284-46cb-84b6-cc64817f46ce">

On MacOS btw. X11 is installed, Xquartz is installed, python, etc

**Comment by gururise** [comment]
I found out that disabling ipv6 and only allowing ipv4 resolved this issue.

Happened 100% of the time if ipv6 was enabled. Running from a VPS.

**Comment by markmcd** [comment]
> I found out that disabling ipv6 and only allowing ipv4 resolved this issue.
> 
> Happened 100% of the time if ipv6 was enabled. Running from a VPS.

That's interesting - can you provide any more info? e.g. the hosting service you used? the v6 block? do you happen to know if curl was connecting via v6 or v4?

I don't think this is expected - Google infra pretty widely supports ipv6 - but just in case there's an infra bug on our end, it'd be good to squash it. I'm trying to narrow down whether it's in the Python support or more broadly.

If you're concerned about sharing any info, but would be willing to share it directly, my email is the first 2 and last 2 characters of my GH username @google.com. It is also in the Git logs in this repo.

**Comment by MarkDaoust** [comment]
@yarub123 

>  I tried the above with transport rest and still getting the error:

That looks like you're trying to run python code in your shell, and it's running some other program called `import`.

**Comment by yarub123** [comment]
@MarkDaoust thanks for following up. Time flies way too damn fast. But yeah, I had to enter the py env first before trying the above import and the api key with "transport." The "transport" code as given above by @markmcd worked. The one with "os.key" in the main readme did not work because I first had to define the variable "os" in order to get it to work. Thank you though.

**Comment by MarkDaoust** [comment]
I heard that they recently removed the region filter. Can you try again?

**Comment by GuHaRaJ** [comment]
@markmcd, I have been facing an error which shows:-
![error](https://github.com/google/generative-ai-python/assets/129865051/c546d2a4-28a4-476a-bcaf-fc7bbc2a04b2)
please can you help me out...

**Comment by markmcd** [comment]
@GuHaRaJ, I think this might be https://github.com/google/generative-ai-python/issues/50, so could you respond over there?

Have you used `gcloud` at all? The client library will try to use the application default credentials if they are available (e.g. because you have run `gcloud auth application-default login ...`), and will do this automatically and transparently.

I listed a possible solution in https://github.com/google/generative-ai-python/issues/50#issuecomment-1648788032 - try that and let me know (on that issue) how it goes.

**Comment by GuHaRaJ** [comment]
@markmcd thanks for helping me out. Basically I am a beginner and could not figure out on how to fix the problem.I found out the title of the issue (**later on changed**) which was matching with my code error , therefore posted my error here. After referring #50 section discussions , i have tried running it in `.venv` mode , and it is working.
Anyways thanks for your concern 🤝...
