### ISSUE TITLE
Why is there a subfolder `google` instead of just having the package `generativeai`?

### ISSUE THREAD

**Issue by nbro** [google/generative-ai-python#34]
My question is in the title. It seems unnecessary to have the folder `google`. Or is there a special reason for this? If this is really unnecessary, I could try to fix it myself. Let me know.

**Comment by markmcd** [comment]
This library is Google's Generative AI library for Python, so it has Google in the name. It also has Generative AI in the name, and where it's useful to distinguish, it has Python in the name.

Product renaming is a significant undertaking, and such requests are beyond the scope of GitHub, so I am closing this. If you have a specific problem that we can help with, please feel free to reopen & state your issue in terms of the problem.
