### ISSUE TITLE
Streaming support?

### ISSUE THREAD

**Issue by logan-markewich** [google/generative-ai-python#43]
Are there plans to support streaming responses from the API?

**Comment by MarkDaoust** [comment]
I've heard there are plans, but I don't have a concrete timeline.

**Comment by MarkDaoust** [comment]
Ack, I'll let you know if I hear anything concrete.

**Comment by alonsosilvaallende** [comment]
My 2 cents: Since OpenAI supports streaming and now ElevenLabs supports [streaming audio](https://twitter.com/elevenlabsio/status/1688638033980014592?s=46&t=kjTAU1JyJnQc4LWjWrQW7Q) I think this feature is needed.

**Comment by ishaan-jaff** [comment]
+1 on this we're trying to add Palm to LiteLLM

**Comment by Danipulok** [comment]
Any news?

**Comment by markmcd** [comment]
Implemented with Gemini - see package version 0.3.0.
