### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by jybaek** [google/generative-ai-python#45]
I am encountering an issue while using the google.generativeai.chat library. Whenever I input the phrase "who are you?" as a message, it consistently triggers an error. This behavior seems unexpected and needs to be addressed.

```python
response = palm.chat(messages=["who are you?"])
# error
  ...
  File "/Users/jybaek/work/xxxx/.venv/lib/python3.8/site-packages/google/generativeai/discuss.py", line 413, in reply
    return _generate_response(request=request, client=self._client)
  File "/Users/jybaek/work/xxxx/.venv/lib/python3.8/site-packages/google/generativeai/discuss.py", line 461, in _generate_response
    return _build_chat_response(request, response, client)
  File "/Users/jybaek/work/xxxx/.venv/lib/python3.8/site-packages/google/generativeai/discuss.py", line 443, in _build_chat_response
    request["messages"].append(response["candidates"][0])
IndexError: list index out of range
```

Is it a known issue? Please check.

**Comment by MarkDaoust** [comment]
I think you're using an older version of the client,  Instead of "List index out of range" this now returns `None`.
That itself is not helpful. 

The API is not returning any candidates for this request:

```
curl -H 'Content-Type: application/json'        \
    -H "x-goog-api-key: ${PALM_API_KEY}"      \
    -d '{"prompt": {"messages": [{"content": "who are you", "author":"0"}]}}'     \
    "https://generativelanguage.googleapis.com/v1beta2/models/chat-bison-001:generateMessage"
```

```
{
  "messages": [
    {
      "author": "0",
      "content": "who are you"
    }
  ],
  "filters": [
    {
      "reason": "OTHER"
    }
  ]
}
```

The owners are aware of the problem.

**Comment by jybaek** [comment]
I found the cause. I was using Python 3.8. When installing `google-generativeai` with `pip install` in Python 3.8, it installs rc1.

Thank you for your help :)

**Comment by MarkDaoust** [comment]
Yeah, I think we've yanked those versions, so you shouldn't see them anymore.
