### ISSUE TITLE
Retry 

### ISSUE THREAD

**Issue by shrimonmuke0202** [google/generative-ai-python#46]
Hi,
How to tackle rate limit error using the retry function?

**Comment by jybaek** [comment]
Try using the [tenacity](https://github.com/jd/tenacity) library.

**Comment by MarkDaoust** [comment]
I'm looking into making that builtin. 

In a lot of the tutorials we use:

```
from google.api_core import retry

@retry.Retry()
def generate_text(*args, **kwargs):
  return palm.generate_text(*args, **kwargs)
```

https://generativeai.devsite.corp.google.com/examples/text_calculator
