### ISSUE TITLE
Response in other language always return None

### ISSUE THREAD

**Issue by BankNatchapol** [google/generative-ai-python#49]
I'm trying to get a response in other languages, but it always return None
```
message = "HELLO!"
prompt = f"""
ANSWER IN CHINESE.
USER:{message}
ASSISTANT:"""

response = palm.chat(
    prompt=prompt
)

print(response.messages) 
```

Chinese
`[{'author': '0', 'content': '\nANSWER IN CHINESE.\nUSER:HELLO!\nASSISTANT:'}, None]`
Thai
`[{'author': '0', 'content': '\nANSWER IN THAI.\nUSER:HELLO!\nASSISTANT:'}, None]`
Japanese
`[{'author': '0', 'content': '\nANSWER IN JAPANESE.\nUSER:HELLO!\nASSISTANT:'}, None]`

**Comment by markmcd** [comment]
PaLM 2 only [supports English](https://developers.generativeai.google/models/language#model_attributes) at this stage.

You can inspect the response object to see that the response was blocked due to a filter:

```python
>>> response = palm.chat(
        prompt=prompt
    )

>>> print(response.filters)
[{'reason': <BlockedReason.OTHER: 2>}]
```
