### ISSUE TITLE
Palm API - 403 Request had insufficient authentication scopes

### ISSUE THREAD

**Issue by hankp46** [google/generative-ai-python#51]
This is similar to issue #50. Running the following:   
import google.generativeai as palm
import os
palm.configure(api_key="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")

response = palm.chat(messages='Hello')

response.last

and receive:
PermissionDenied: 403 Request had insufficient authentication scopes. [reason: "ACCESS_TOKEN_SCOPE_INSUFFICIENT"
domain: "googleapis.com"
metadata {
  key: "method"
  value: "google.ai.generativelanguage.v1beta2.DiscussService.GenerateMessage"
}
metadata {
  key: "service"
  value: "generativelanguage.googleapis.com"
}
I get successful results running the curl example.
I have run it under 2 Python environments
I'm a fairly new user but it seems to me that it can't find "google.ai.generativelanguage.v1beta2.DiscussService.GenerateMessage"

I was approved for the beta test. Tried to add the scope: https://www.googleapis.com/auth/generative-language but it could not be found.
Don't know what more steps I can take

**Comment by hankp46** [comment]
I finally go it working on a different computer. I suspect there is something corrupt in one of the modules. Trying now to remove all the pieces from the problem computer. Not sure how to do it It seems a pip uninstall does not get rid of everything since I get the same error after installing again.

**Comment by hankp46** [comment]
Finally got it working on both computers. Had to do the following: Created a req.txt file containing the following modules:
cachetools-5.3.1 google-ai-generativelanguage-0.2.0 google-api-core-2.11.1 google-auth-2.22.0 google-generativeai-0.1.0 googleapis-common-protos-1.59.1 grpcio-1.56.2 grpcio-status-1.56.2 proto-plus-1.22.3 protobuf-4.23.4 pyasn1-0.5.0 pyasn1-modules-0.3.0 rsa-4.9
Ran:
pip uninstall -y -r reqs.txt
 pip install google-generativeai

**Comment by chissom** [comment]
I'm facing the same error, could you give me a guide please.
how did you got this " XXXXXXXXX/.config/gcloud/application_default_credentials.json' "
