### ISSUE TITLE
Safety filter is too strong today

### ISSUE THREAD

**Issue by xiaohk** [google/generative-ai-python#65]
### Description of the bug:

Hello, I am using the PaLM API through Python / JS and MakerSuite. I noticed that the safety filter has become unexpectedly strong recently. My very benign inference requests were all responded with `{reason: "OTHER"}`. Is there a way to change my safety setting to get the result?

Here is an example in MakerSuite (I have already lowered the safety filter thresholds, see screenshot 2):

<img width="1019" alt="image" src="https://github.com/google/generative-ai-python/assets/15007159/a3b9a70a-35a4-4e00-a152-9fe1b90566f9">

<img width="1106" alt="image" src="https://github.com/google/generative-ai-python/assets/15007159/7f03c886-8015-4b66-8924-287abfddd417">

### Actual vs expected behavior:

I expect to get result "comment vas-tu ?" instead of an empty response with `OTHER` reason. I believe PaLM 2 API used to give me this correct response two days ago.

**Comment by xiaohk** [comment]
I used [this MakerSuite prompt](https://makersuite.google.com/app/prompts?state=%7B%22ids%22%3A%5B%2212rSZSpusXD4-H4tHBdXwjxQVDhQTg4pb%22%5D%2C%22action%22%3A%22open%22%2C%22userId%22%3A%22100199190440290095489%22%2C%22resourceKeys%22%3A%7B%7D%7D&usp=sharing).

**Comment by xiaohk** [comment]
I believe PaLM 2 is designed to support better translation, so it would be great if PaLM 2 API users can use the model for translation tasks. See section 4.2 in the [PaLM 2 technical report](https://arxiv.org/abs/2305.10403).

> An explicit design choice of PaLM 2 is an improved translation capability.

<img width="902" alt="image" src="https://github.com/google/generative-ai-python/assets/15007159/72ee2251-1b47-4fc7-a512-50fe19c9947b">

**Comment by williamito** [comment]
Hi there; this PaLM API only supports English at the moment (https://developers.generativeai.google/models/language#model_attributes) so translation use cases are not supported.

**Comment by xiaohk** [comment]
I see, thank you for the reply. @williamito
