### ISSUE TITLE
support application default credentials

### ISSUE THREAD

**Issue by pascalwhoop** [google/generative-ai-python#8]
https://cloud.google.com/docs/authentication/provide-credentials-adc

Are you supporting the default credentials for GCP APIs? From the code it looks like you require an api_key to be passed

**Comment by pascalwhoop** [comment]
Actually, can you help explain the relation to this framework?

https://pypi.org/project/google-cloud-aiplatform/

Given the GCP console gives me the below snippet to leverage PaLM, what is the purpose of this library (which apparently is used by the Langchain library as well)

```
import vertexai
from vertexai.preview.language_models import ChatModel, InputOutputTextPair

def predict_large_language_model_sample(
    project_id: str,
    model_name: str,
    temperature: float,
    max_output_tokens: int,
    top_p: float,
    top_k: int,
    location: str = "us-central1",
    ) :
    """Predict using a Large Language Model."""
    vertexai.init(project=project_id, location=location)

    chat_model = ChatModel.from_pretrained(model_name)
    parameters = {
      "temperature": temperature,
      "max_output_tokens": max_output_tokens,
      "top_p": top_p,
      "top_k": top_k,
    }

    chat = chat_model.start_chat(
      examples=[]
    )


predict_large_language_model_sample("3972195257", "chat-bison@001", 0.2, 256, 0.8, 40, "us-central1")
```

**Comment by markmcd** [comment]
This is unfortunately a known issue with the underlying API. Thanks for reporting it, I'll pass it on to the API team.

The Vertex API is a different, complementary, product for Google Cloud.

**Comment by pascalwhoop** [comment]
Actually, we have early access to PaLM but are not able to make it work via API, would you mind sharing an example of how this library is supposed to be used (since langchain also builds on top of this it seems)

**Comment by MarkDaoust** [comment]
>  we have early access to PaLM but are not able to make it work via API

If the API is enabled for your project, and you've generated an API key, you can pass the key to `palm.configure(api_key=...)`, or set it as the `GOOGLE_API_KEY` environment variable.

For examples of how to use this library see the tutorials on the site:

https://developers.generativeai.google/tutorials/chat_quickstart
https://developers.generativeai.google/tutorials/text_quickstart
https://developers.generativeai.google/tutorials/embedding_quickstart

**Comment by markmcd** [comment]
In addition to Mark's comment, to use application default credentials you can set it up like so:

```bash
gcloud config set account your@account.com
gcloud config set project name-of-your-cloud-project

gcloud auth application-default login --scopes="https://www.googleapis.com/auth/generative-language,https://www.googleapis.com/auth/cloud-platform"
```

After running the above, the client library/ies should work transparently. REST calls will need headers set:
```bash
curl -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
      -H "X-Goog-User-Project: $(gcloud config get project)" -X GET \
      "https://generativelanguage.googleapis.com/v1beta2/models"
```

**Comment by abitrolly** [comment]
@markmcd if there a way to check which scopes are already enabled for ADc?

```python
google.api_core.exceptions.PermissionDenied: 403 Request had insufficient authentication scopes. [reason: "ACCESS_TOKEN_SCOPE_INSUFFICIENT"
domain: "googleapis.com"
metadata {
  key: "service"
  value: "generativelanguage.googleapis.com"
}
metadata {
  key: "method"
  value: "google.ai.generativelanguage.v1beta.ModelService.ListModels"
}
]
```

**Comment by abitrolly** [comment]
I asked Google Gemini in Cloud console and it gave me some fantasies, like:

![image](https://github.com/google/generative-ai-python/assets/8781107/6036957e-2595-480e-81f7-ea9c56ee5bd1)

The problem is that command doesn't exist. Opened the issue here.

https://issuetracker.google.com/issues/335383223

Maybe there is another way to check?

**Comment by MarkEdmondson1234** [comment]
I tried this and got :

Some requested scopes cannot be shown: [https://www.googleapis.com/auth/generative-language]

**Comment by MarkDaoust** [comment]
@MarkEdmondson1234 - did you configure your project like described here: https://ai.google.dev/gemini-api/docs/oauth#set-cloud

**Comment by GiladDuani** [comment]
hello 
it seems like this is still a problem 
is there any docs of how it can be fixed or an estimated time for a fix?
