### ISSUE TITLE
API key from MakerSuite Access Denied 

### ISSUE THREAD

**Issue by gzhelev2020** [google/generative-ai-python#80]
### Description of the bug:

When getting an API-Key I get a message that the access restricted. I think I would need that Key to be able to install and use the API. Is it possibly my Administartor who is blocking me? I would need to try this on my personal laptop.

**Comment by keertk** [comment]
Hi @gzhelev2020 which region are you trying to access MakerSuite / the API key from?
It's only available in the following regions at the moment: https://developers.generativeai.google/available_regions

**Comment by MarioRasconMerinoML** [comment]
Why is not available in any EU country?
