### ISSUE TITLE
google-generativeai Installation on Render Linux Servers

### ISSUE THREAD

**Issue by Ronlin1** [google/generative-ai-python#84]
### Description of the bug:

ERROR: No matching distribution found for google-generativeai 

### Any other information you'd like to share?

I am trying to install it from the requirements.txt file on render.com

**Comment by markmcd** [comment]
Can you provide any more info? I'm not familiar with render.com so am not sure how to reproduce this. More detailed repro steps would help.

Or alternatively can you provide any info at all about the platform? e.g. python version, anything else that's in `requirements.txt`, any custom index that might in use, etc.

**Comment by kennethdave** [comment]
Is there any update on this? 
Collecting google-generativeai
  Could not find a version that satisfies the requirement google-generativeai (from versions: )
No matching distribution found for google-generativeai

**Comment by markmcd** [comment]
@kennethdave - we still need the info I asked for in my last comment. This library is available for Python 3.9-3.11 - can you tell us what version you are trying to install it into? If it's one of the supported versions, what platform are you using? (e.g. CPython, windows, etc)

**Comment by kennethdave** [comment]
Hi @markmcd I'm using 3.7 thus will do an upgrade. Thank you
